### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by c-bata** [c-bata/goptuna#1]
Goptuna currently supports the minimum required features only.

* Sampler
    * [x] RandomSearchSampler
    * [x] TPESampler
* Storage
    * [x] In-memory storage backend
* Distribution
    * [x] UniformDistribution
    * [x] LogUniformDistribution
    * [x] DiscreteUniformDistribution
    * [x] IntUniformDistribution
    * [x] CategoricalDistribution
* Examples
    * [x] Add basic example
    * [x] Add example of parallel optimization

**Comment by c-bata** [comment]
All basic features are implemented :tada:
